<?php

/**
 * This file is part of the spryker-community/search-analyzer-config package.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace SprykerCommunityTest\Zed\SearchAnalyzerConfig\Persistence\Mapper;

use Codeception\Test\Unit;
use DateTime;
use Generated\Shared\Transfer\SearchAnalyzerConfigTermTransfer;
use Generated\Shared\Transfer\SearchAnalyzerConfigTransfer;
use Orm\Zed\SearchAnalyzerConfig\Persistence\SpySearchAnalyzerConfig;
use Orm\Zed\SearchAnalyzerConfig\Persistence\SpySearchAnalyzerConfigTerm;
use SprykerCommunity\Zed\SearchAnalyzerConfig\Persistence\Mapper\SearchAnalyzerConfigMapper;

/**
 * Auto-generated group annotations
 *
 * @group SprykerCommunityTest
 * @group Zed
 * @group SearchAnalyzerConfig
 * @group Persistence
 * @group Mapper
 * @group SearchAnalyzerConfigMapperTest
 *
 * Not @group Portable: unlike Copier/Renderer/Validator (pure logic against Transfer objects only),
 * this test constructs Orm\Zed\SearchAnalyzerConfig\Persistence\* Propel entities directly. Those
 * classes are generated by a host shop's `propel:model:build` against a real schema + database (see
 * tools/floor-check.php's HOST_GENERATED_ORM_PREFIX) and don't exist in the standalone CI checkout at
 * all, so this suite can only run from a host shop, same as the EntityManager/Repository/Facade tests.
 */
class SearchAnalyzerConfigMapperTest extends Unit
{
    public function testMapEntityToTransferCopiesEveryScalarColumn(): void
    {
        $appliedAt = new DateTime('2026-08-01 12:00:00');

        $spySearchAnalyzerConfig = (new SpySearchAnalyzerConfig())
            ->setIdSearchAnalyzerConfig(42)
            ->setSourceIdentifier('page')
            ->setStoreName('DE')
            ->setStemmerLanguage('light_german')
            ->setNormalizationFilter('german_normalization')
            ->setStopwordsMode('builtin')
            ->setStopwordsBuiltinLanguage('_german_')
            ->setDecompoundEnabled(true)
            ->setRevision(3)
            ->setAppliedRevision(2)
            ->setAppliedIndexName('de_page_20260801120000')
            ->setAppliedAt($appliedAt);

        $searchAnalyzerConfigTransfer = (new SearchAnalyzerConfigMapper())->mapEntityToTransfer(
            $spySearchAnalyzerConfig,
            new SearchAnalyzerConfigTransfer(),
        );

        $this->assertSame(42, $searchAnalyzerConfigTransfer->getIdSearchAnalyzerConfig());
        $this->assertSame('page', $searchAnalyzerConfigTransfer->getSourceIdentifier());
        $this->assertSame('DE', $searchAnalyzerConfigTransfer->getStoreName());
        $this->assertSame('light_german', $searchAnalyzerConfigTransfer->getStemmerLanguage());
        $this->assertSame('german_normalization', $searchAnalyzerConfigTransfer->getNormalizationFilter());
        $this->assertSame('builtin', $searchAnalyzerConfigTransfer->getStopwordsMode());
        $this->assertSame('_german_', $searchAnalyzerConfigTransfer->getStopwordsBuiltinLanguage());
        $this->assertTrue($searchAnalyzerConfigTransfer->getDecompoundEnabled());
        $this->assertSame(3, $searchAnalyzerConfigTransfer->getRevision());
        $this->assertSame(2, $searchAnalyzerConfigTransfer->getAppliedRevision());
        $this->assertSame('de_page_20260801120000', $searchAnalyzerConfigTransfer->getAppliedIndexName());
        $this->assertSame($appliedAt->format(DATE_ATOM), $searchAnalyzerConfigTransfer->getAppliedAt());
    }

    public function testMapEntityToTransferHandlesNullAppliedAt(): void
    {
        $spySearchAnalyzerConfig = (new SpySearchAnalyzerConfig())
            ->setSourceIdentifier('page')
            ->setStoreName('DE');

        $searchAnalyzerConfigTransfer = (new SearchAnalyzerConfigMapper())->mapEntityToTransfer(
            $spySearchAnalyzerConfig,
            new SearchAnalyzerConfigTransfer(),
        );

        $this->assertNull($searchAnalyzerConfigTransfer->getAppliedAt());
    }

    public function testMapTermEntityToTransferCopiesEveryColumn(): void
    {
        $spySearchAnalyzerConfigTerm = (new SpySearchAnalyzerConfigTerm())
            ->setIdSearchAnalyzerConfigTerm(7)
            ->setListType('synonym')
            ->setTerm('sofa, couch')
            ->setSortOrder(2);

        $searchAnalyzerConfigTermTransfer = (new SearchAnalyzerConfigMapper())->mapTermEntityToTransfer(
            $spySearchAnalyzerConfigTerm,
            new SearchAnalyzerConfigTermTransfer(),
        );

        $this->assertSame(7, $searchAnalyzerConfigTermTransfer->getIdSearchAnalyzerConfigTerm());
        $this->assertSame('synonym', $searchAnalyzerConfigTermTransfer->getListType());
        $this->assertSame('sofa, couch', $searchAnalyzerConfigTermTransfer->getTerm());
        $this->assertSame(2, $searchAnalyzerConfigTermTransfer->getSortOrder());
    }
}
